#!/usr/bin/env bash

function value_or_empty() {
  [ "$1" -eq 1 ] && echo "123" || echo "${2}"
}

SCRIPT_DIR=$(echo "${BASH_SOURCE[0]}" | xargs dirname | xargs -I % sh -c 'cd % && pwd')
PROJECT_ROOT="${SCRIPT_DIR}/.."
SECRETS_FILE="${PROJECT_ROOT}/CouchTrackerApp/Utils/Secrets.swift"

EMPTY=0; [ "$1" == "empty" ] && EMPTY=1

TRAKT_CLIENT_ID=$(value_or_empty "${EMPTY}" "${COUCH_TRACKER_TRAKT_CLIENT_ID}")
TRAKT_CLIENT_SECRET=$(value_or_empty "${EMPTY}" "${COUCH_TRACKER_TRAKT_CLIENT_SECRET}")
TRAKT_REDIRECT_URL=$(value_or_empty "${EMPTY}" "${COUCH_TRACKER_TRAKT_REDIRECT_URL}")
TMDB_API_KEY=$(value_or_empty "${EMPTY}" "${COUCH_TRACKER_TMDB_API_KEY}")
TVDB_API_KEY=$(value_or_empty "${EMPTY}" "${COUCH_TRACKER_TVDB_API_KEY}")
BUGSNAG_KEY=$(value_or_empty "${EMPTY}" "${BUGSNAG_API_KEY}")

cat > "$SECRETS_FILE" << EOF
enum Secrets {
  enum Trakt {
    static let clientId = "${TRAKT_CLIENT_ID}"
    static let clientSecret = "${TRAKT_CLIENT_SECRET}"
    static let redirectURL = "${TRAKT_REDIRECT_URL}"
  }

  enum TMDB {
    static let apiKey = "${TMDB_API_KEY}"
  }

  enum TVDB {
    static let apiKey = "${TVDB_API_KEY}"
  }

  enum Bugsnag {
    static let apiKey = "${BUGSNAG_KEY}"
  }
}
EOF
