#!/usr/bin/env bash

SCRIPT_DIR=$(echo "${BASH_SOURCE[0]}" | xargs dirname | xargs -I % sh -c 'cd % && pwd')
PROJECT_ROOT="${SCRIPT_DIR}/.."
SECRETS_FILE="${PROJECT_ROOT}/CouchTrackerApp/Utils/Secrets.swift"
CRASHLYTICS_API_KEY_FILE="${PROJECT_ROOT}/build_phases/crashlytics.apikey"
CRASHLYTICS_API_SECRET_FILE="${PROJECT_ROOT}/build_phases/crashlytics.apisecret"

cat > "$SECRETS_FILE" << EOF
enum Secrets {
  enum Trakt {
    static let clientId = "${COUCH_TRACKER_TRAKT_CLIENT_ID}"
    static let clientSecret = "${COUCH_TRACKER_TRAKT_CLIENT_SECRET}"
    static let redirectURL = "${COUCH_TRACKER_TRAKT_REDIRECT_URL}"
  }

  enum TMDB {
    static let apiKey = "${COUCH_TRACKER_TMDB_API_KEY}"
  }

  enum TVDB {
    static let apiKey = "${COUCH_TRACKER_TVDB_API_KEY}"
  }

  enum Crashlytics {
    static let apiKey = "${CRASHLYTICS_API_KEY}"
  }
}
EOF

cat > "${CRASHLYTICS_API_KEY_FILE}" << EOF
$CRASHLYTICS_API_KEY
EOF

cat > "${CRASHLYTICS_API_SECRET_FILE}" << EOF
$CRASHLYTICS_API_SECRET
EOF
