#!/bin/bash

swiftformat --indent 2 CouchTracker/
swiftformat --indent 2 CouchTrackerApp/
swiftformat --indent 2 CouchTrackerCore/
swiftformat --indent 2 CouchTrackerCoreTests/
swiftformat --indent 2 CouchTrackerPersistence/
