#!/usr/bin/env bash

SCRIPT_DIR=$(echo "${BASH_SOURCE[0]}" | xargs dirname | xargs -I % sh -c 'cd % && pwd')
PROJECT_ROOT=$(cd "${SCRIPT_DIR}/.." && pwd)

cd "${PROJECT_ROOT}" || exit 1

FOLDERS=("CouchTracker/" "CouchTrackerApp/" "CouchTrackerCore/" "CouchTrackerCoreTests/"
"CouchTrackerPersistence/" "CouchTrackerDebug/" "TraktSwift/" "TraktSwiftTests/"
"TMDBSwift/" "TMDBSwiftTests/" "TVDBSwift/" "TVDBSwiftTests/")

for folder in ${FOLDERS[*]}; do
    swiftformat --indent 2 "${folder}"
done
